packages:
  - host
  - realm-server
  - worker
  - cards
  - base
  - runtime-common
  - vendor/ember-template-imports
  - vendor/ember-concurrency-async-plugin
  - vendor/transform-modules-amd-plugin
