name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.6.0
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm --version
      - run: pnpm install --frozen-lockfile
      - run: pnpm glint
      - run: cd ./worker && pnpm tsc
      - run: cd ./realm-server && pnpm tsc
  host-test:
    name: Host Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.6.0
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm --version
      - run: pnpm install --frozen-lockfile
      - name: Start realm servers
        run: pnpm start:test-realms &
        working-directory: realm-server
      - name: host test suite
        run: pnpm test:ember
        working-directory: host
  realm-test:
    name: Realm Server Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.6.0
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm --version
      - run: pnpm install --frozen-lockfile
      - name: Start base realm server
        run: pnpm start:test-realms &
        working-directory: realm-server
      - name: Wait for server to start
        run: sleep 5
      - name: realm server test suite
        run: pnpm test
        working-directory: realm-server
